# 1주차

In [1]:
#1-1
number = int(input("자연수를 입력하세요"))
if number % 2 == 0:
    print(number, "is even")
else :
    print(number, "is odd")

5 is odd


# 2주차

In [3]:
#2-1
num = "881120-1068234"
#다음 코드 부분을 완성해 보세요.
date = num[:6]          #생년월일 슬라이싱
id_num =  num[7:]       # 뒤의 숫자 부분 슬라이싱
print(date)
print(id_num)

881120
1068234


In [5]:
#2-2
pin = '881120-1068234'
# 다음 코드를 완성하세요.
key_1 = pin[7] #성별 부분 인덱싱
print(key_1)

1


In [6]:
#2-3
#다음 코드를 완성하시오.
char_1 = "a:b:c:d"
char_1.replace(':','#')           #replace는 괄호안에 ('문자열1', '문자열2')와 같이 써서 문자열1을 문자열2로 바꾼다.

'a#b#c#d'

In [13]:
# 코드를 완성하세요.
char_2 = char_1.split(":")  # 문자열.split(나누는 기준)
print(char_2)
char_3 = '#'.join(char_2)            #문자열.join(리스트명)
char_3

['a', 'b', 'c', 'd']


'a#b#c#d'

In [17]:
#2-4
# 다음 코드를 완성하시오.
fah = [70, 55, 45, 40, 37, 32, 20, 18, 20]
ind_1 = int(input("몇번을 섭씨로 바꿀까요?"))
celci = 5/9 *(fah[ind_1]-32)
print(f'{ind_1} 번 화씨를 섭씨로 바꾸면 {celci :.4f}')

3 번 화씨를 섭씨로 바꾸면 4.4444


In [18]:
# 2-5
cha = ['Life', 'is', 'too', 'short']
#다음을 완성하시오. join 함수를 사용하세요.
print(" ".join(cha))

Life is too short


In [25]:
# 2-6
a = [1, 3, 5, 4, 2]
#다음을 완성하시오.
a.sort()
a.reverse()
print(a)


[5, 4, 3, 2, 1]


In [29]:
#2-7

a = (1, 2, 3)
# 아래에 코드를 완성하시오.
new = (4,)
a+new


(1, 2, 3, 4)

In [30]:
# 2-8
# 다음 코드를 완성하시오.
dict1 = {'name' : '홍길동',
         'birth' : 1128,
         'age' : 30}

In [31]:
#2-9
a = {'A' : 90, 'B' : 80}
#다음 코드를 완성하시오
a.get('C', 70)

70

In [37]:
#2-10
a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]

list(set(a))


[1, 2, 3, 4, 5]

In [38]:
# 2-11
import numpy as np
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
              # 7은 2행 3열
# 1)
m[1,2]

7

In [39]:
#2)
m[2,4]

14

In [41]:
#3)
m[1,1:3]

array([6, 7])

In [43]:
#4)
m[1:3,2]

array([ 7, 12])

In [44]:
#5)
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

# 3주차

In [45]:
# 3-1
#아래 코드를 완성하시오.
fruit =["사과", "포도", "홍시"]
user_fruit = input("좋아하는 과일은? ")

if  user_fruit in fruit:   # 이 부분을 완성하시오
    print("정답입니다")
else :
    print("오답입니다")            # 이 부분을 완성하시오.

정답입니다


In [46]:
#3-2
grade = int(input("Score를 입력하세요: "))

if grade >=81 and grade <=100:
    print("grade is A")
elif  grade >= 61  :
    print("grade is B")
elif  grade >= 41     :
    print("grade is C")
elif  grade >=21     :
    print("grade is D")
else:
    print("grade is E")

grade is D


In [47]:
#3-3
idx = [2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5]
num = input("주민등록번호를 입력하시오: (xxxxxx-xxxxxxx형태로)")
num = num.replace('-', '')
num

'0110213035118'

In [50]:
s = 0
for i in range(12):
    s += int(num[i])*idx[i]         # s+= 은 s=s+

mod = s % 11
c = (11-mod) % 10   # 이 부분을 채우시오.

if  c == num[12] :  #이 부분을 채우시오.
    print("유효한 주민등록번호 입니다.")
else:
    print("유효하지 않은 주민등록번호입니다. ")

유효하지 않은 주민등록번호입니다. 


In [51]:
#3-4
num = int(input("구매할 상품 개수를 입력하시오: "))

if  num<10: #10개 미만
    price = 100
elif num>= 10 and num <30:
    price = 95
elif  num>=30 and num<100         :
    price = 90
elif  num>=100     :
    price = 85

pay = price * num
print(f"총 지불해야할 가격은 {pay}원입니다.")

총 지불해야할 가격은 200원입니다.


In [52]:
#3-5
year = int(input("년도를 입력하시오: "))

if year % 400 ==0 : # 400으로 나누어 떨어지는 해는 윤년
    print(f"{year}년은 윤년이다.")
elif year % 100==0 : #100으로 나누어 떨어지고 400으로 나누어 지지 않는 해는 평년
    print(f"{year}년은 윤년이 아니다.")
elif year%4 == 0: # 100으로 나누어 지지 않고 4로 나누어 떨어지는 해는 윤년
    print(f"{year}년은 윤년이다.")
else :
    print(f"{year}년은 윤년이 아니다.")

2016년은 윤년이다.


In [53]:
#3-6
year = int(input("년도를 입력하시오: "))
month = int(input("월을 입력하시오: "))

if month in [1, 3, 5, 7, 8,10, 12]: # 그 달이 1, 3, 5, 7, 8, 10, 12월이면 31일
    print(f"{month}월은 31일까지 있다.")
elif  month in   [4, 6, 9, 11]: #30일인 달
    print(f"{month}월은 30일까지 있다.")
else:
    if  year % 400 ==0         : #위의 과정을 참고해서 코드를 채울 것
        print(f"{month}월은 29일까지 있다.")
    elif year % 100==0        :
        print(f"{month}월은 28일까지 있다.")
    elif  year%4 == 0       :
        print(f"{month}월은 29일까지 있다.")
    else  :
        print(f"{month}월은 28일까지 있다.")


2월은 29일까지 있다.


In [54]:
#3-7
i = 1
total = 0
while   i <1001    :
    if i%3==0      : # 3의 배수이면 ?
        total += i
    i +=1


print(f"1부터 1000까지의 자연수 중 3의 배수의 합은 {total}이다.")

1부터 1000까지의 자연수 중 3의 배수의 합은 166833이다.


In [62]:
#3-8
A = [20,55,67,82,45,33,90,87,100,25]
i = 0
total = 0
while i < len(A)   :
    if  A[i] >=50    :
        total += A[i]
    i=i+1


print(total)

481


In [63]:
#3-9
i = 1
while  1 :
    print( "*"*i   )
    i+=1        # i를 키워줘야 함.
    if i ==11:
        break


*
**
***
****
*****
******
*******
********
*********
**********


In [64]:
#3-10
total = 0
i = 100
while i<10000:
    if i% 5 ==0:
        total+= i
    i+=1



print(total)

9994050


In [66]:
#3-11
for i in range(1,101):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

In [67]:
#3-12
A = [70,60,55,75,95,90,80,80,85,100]
total = 0
for i in A:
    total+=i


average = total / len(A)
print(f"A학급의 평균 점수는 {average}이다.")

A학급의 평균 점수는 79.0이다.


In [68]:
# 3-13
numbers = []

for i in range(1, 101):
    numbers.append(i)

for i in range(100) :
    if "3" in str(numbers[i]):
        numbers[i] = "*"
    if  "6" in str(numbers[i]) :
        numbers[i] = "*"
    if   "9" in str(numbers[i]) :
        numbers[i] = "*"


print(numbers)

[1, 2, '*', 4, 5, '*', 7, 8, '*', 10, 11, 12, '*', 14, 15, '*', 17, 18, '*', 20, 21, 22, '*', 24, 25, '*', 27, 28, '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', 40, 41, 42, '*', 44, 45, '*', 47, 48, '*', 50, 51, 52, '*', 54, 55, '*', 57, 58, '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', 70, 71, 72, '*', 74, 75, '*', 77, 78, '*', 80, 81, 82, '*', 84, 85, '*', 87, 88, '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', 100]


In [69]:
#3-14
sum = 0
for i in range(1,101):
    if (i % 3==0) or (i%4==0)  :
        sum += i


print(sum)

2551


In [71]:
import random

a= [random.randint(0,100) for value in range(0,20)]  
a

[81,
 65,
 35,
 41,
 33,
 46,
 32,
 90,
 64,
 96,
 39,
 47,
 19,
 37,
 41,
 53,
 25,
 82,
 16,
 93]

In [93]:
#3-15
import random

"""a= [random.randint(0,100) for value in range(0,20)]           # 무작위 리스트 생성하는 법!!!!!!!!!!
max = a[0]
for i in range(1, 20)     :
    if  max > a[i]   :
        continue
    else:
        max = a[i]


print(f"리스트: {a}\n최대값: {max}")"""


'a= [random.randint(0,100) for value in range(0,20)]           # 무작위 리스트 생성하는 법!!!!!!!!!!\nmax = a[0]\nfor i in range(1, 20)     :\n    if  max > a[i]   :\n        continue\n    else:\n        max = a[i]\n\n\nprint(f"리스트: {a}\n최대값: {max}")'

# 4주차

In [73]:
# 4-1
def is_odd(num) :
    if  num%2==0  :   #여기에 알맞은 코드를 적으시오.
        print("%d 짝수입니다"% num)

    else :
        print("홀수입니다")

is_odd(234)

234 짝수입니다


In [76]:
#4-2
def mean_value(*args) :
    result = 0
    for i in args :
        result+= i      #여기에 알맞은 코드를 넣으시오.

    return   result/len(args)     #여기에 알밪은 코드를 넣으시오.

mean_value(1, 2, 3, 4, 5, 6, 7)

4.0

In [78]:
#4-3

def quo_and_rem(a, b) :
    return    a//b, a%b         #여기에 알맞은 코드를 넣으시오.

quo_and_rem(12, 5)

(2, 2)

In [79]:
#4-4
def is_gugu(n) :
    for  i in range(1, 10)         :
        print(n*i, end=' ')  # 알맞은 코드를 넣으시오.

is_gugu(4)

4 8 12 16 20 24 28 32 36 

In [80]:
#4-5
def fib(n):
    """n번째 피보나치 수를 반환한다."""
    if n == 1:     # 첫 번째 피보나치 수는 1
        return 1
    elif n == 2:   # 두 번째 피보나치 수는 1
        return 1
    else:          # 그 후의 피보나치 수
        return  fib(n-1) +fib(n-2)       #여기에 알맞은 코드를 넣으시오.

fib(20)

6765

In [81]:
#4-6
def grading(num) :
    "등급 주는 함수"
    if  num >=90:  #여기에 알맞은 코드를 넣으시오.
        return "A"
    elif num >= 80 :
        return "B"
    elif num >= 70 :
        return "C"
    elif num >= 60 :
        return "D"
    else :
        return num     #여기에 알맞은 코드를 넣으시오.
num = int(input("당신의 점수는?"))
print(f'{num}점은 {grading(num)} 입니다. ') #여기에 알맞은 코드를 넣으시오.

80점은 B 입니다. 


In [83]:
#4-7
try:
    number = int(input("자연수를 입력하세요 "))
    if number %2 ==0:
        print("짝수")
    else:
        print("홀수")

except ValueError    :
    print("자연수를 입력하세요")



자연수를 입력하세요


In [84]:
#4-8
def check_prime(n):
    try:
        if n !=2:
            for i in range(1,n-1)  :  #적당한 코드를 넣으시오.
                if  n%i ==0 :   #적당한 코드를 넣으시오.
                    print("소수가 아닙니다")
                    break
                elif i == n-1 :
                    print("소수입니다")
        else:
            print("소수입니다.")
    except  ValueError     :
        print("자연수를 입력하세요")

check_prime(10)

소수가 아닙니다


In [2]:
#4-9
def factorization_prime(n):
    """1보다 큰 자연수 n을 변수로 받아 소인수분해 하는 함수"""
    a = []

    while n != 1:
        for i in range(2, n + 1):  # 적당한 코드를 넣으시오.
            if n%i == 0:
                a.append(i)
                n = n // i  # 적당한 코드를 넣으시오.
                break
    return a


print(factorization_prime(43286))

[2, 23, 941]


In [3]:
def ugly_number(n):
    result = factorization_prime(n)

    if max(result) > 5:                 ######리스트에서 최소 최대 찾기 적당한 코드를 넣으시오.
        print("못난이 수가 아닙니다.")

    else:
        print("못난이 수입니다.")

ugly_number(18)

못난이 수입니다.


In [7]:
from string import ascii_lowercase
#string 모듈에 있는 ascii_lowercase 를 사용하면 소문자를 불러올 수 있습니다. print(ascii_lowercase)를 실행하면 볼 수 있습니다.

def caesar():
    alpha = list(ascii_lowercase.upper())               #알파벳 대문자 리스트
    move = int(input('원하는 평행 이동을 적으시오: '))
    message = input('보내고 싶은 메시지는?: ')
    message_list = list(message)

    k=0

    for i in message_list:
        index = alpha.index(i)                        #alpha.index(i)는 alpha라는 리스트의 i의 위치를 반환
        new_index = (index + move) % 26                    #위에 찾은 것과 move를 더한 후 26으로 나눈 나머지로 새 index
        message_list[k] = alpha[new_index]
        k +=1
    return message_list

print(caesar())

['D', 'E']


In [4]:
def colla() :
    numb = int(input('임의의 자연수를 입력하시오: '))

    while True:
        print(numb)
        if numb == 1:
            break
        elif numb % 2 == 0:  # 적당한 코드를 넣으시오. (짝수인 경우)
            numb = int(numb / 2)  # 또는 numb // 2
            continue
        elif numb % 2 == 1:  # 적당한 코드를 넣으시오. (홀수인 경우)
            numb = numb * 3 + 1
            continue

colla()

45
136
68
34
17
52
26
13
40
20
10
5
16
8
4
2
1
